server:
  port: 8082
spring:
  redis:
    database: 2
    host: 44.87.9.186
    open: true # 是否开启redis缓存  true开启   false关闭
    port: 6379
    timeout: 5000s  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 1000  #连接池中的最大空闲连接
        max-wait: -1s #连接池最大阻塞等待时间（使用负值表示没有限制)
        min-idle: 0  #连接池中的最小空闲连接
